### ISSUE TITLE
Apply to Netlify Open Source Plan?

### ISSUE THREAD

**Issue by arschles** [pdxgo/PDXGo-Hugo-Website#2]
Netlify has an open source plan that gives you a site with contributors free of charge. It's approximately the same as their "pro" plan. There are a few requirements that are fairly easy to meet. Apply here: https://www.netlify.com/legal/open-source-policy/

**Comment by brainsnail** [comment]
Applied and added a link to the site they have hosted. Will follow up once I hear something back.

**Comment by brainsnail** [comment]
Looks like we just need to find a good spot to display the Netlify [badge](https://www.netlify.com/press/#badges) on there.

**Comment by brainsnail** [comment]
Hacked at the theme a bit and got the link there now. Sent Netlify an email back and will update again once I get approval from them.

**Comment by brainsnail** [comment]
🎉  Site is moved over and invites sent out. Closing this.
